# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ddfyh

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f6555e08cbbf497282e30b567c7db8f1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_53f7c3f987254bb790147061e1d9f457 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f6555e08cbbf497282e30b567c7db8f1 }}/nmb:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ddfyh'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3c22e7e14ca54dddb39a54f64dcd09ca }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f6555e08cbbf497282e30b567c7db8f1 }}/nmb:${{ github.sha }}'